{
 "title": "mosdns",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Forward Counter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Query vs cache",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "mosdns_plugin_cache_hit_total{instance=\"localhost:9080\"}",
     "legendFormat": "cache hit"
    },
    {
     "expr": "mosdns_plugin_cache_lazy_hit_total{instance=\"localhost:9080\"}",
     "legendFormat": "lazy hit"
    },
    {
     "expr": "mosdns_plugin_cache_query_total{instance=\"localhost:9080\"}",
     "legendFormat": "query"
    }
   ]
  },
  {
   "title": "1-alidns",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "mosdns_plugin_alidns_counter_query_total",
     "legendFormat": "queue {{instance}}"
    },
    {
     "expr": "mosdns_plugin_alidns_counter_err_total",
     "legendFormat": "error {{instance}}"
    }
   ]
  },
  {
   "title": "2-google",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "mosdns_plugin_google_counter_query_total",
     "legendFormat": "queue {{instance}}"
    },
    {
     "expr": "mosdns_plugin_google_counter_err_total",
     "legendFormat": "error {{instance}}"
    }
   ]
  },
  {
   "title": "3-tunadns",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "mosdns_plugin_backup_counter_query_total",
     "legendFormat": "queue {{instance}}"
    },
    {
     "expr": "mosdns_plugin_backup_counter_err_total",
     "legendFormat": "error {{instance}}"
    }
   ]
  },
  {
   "title": "Query vs upstream",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mosdns_plugin_alidns_counter_query_total",
     "legendFormat": "alidns"
    },
    {
     "expr": "mosdns_plugin_google_counter_query_total",
     "legendFormat": "google"
    },
    {
     "expr": "mosdns_plugin_backup_counter_query_total",
     "legendFormat": "tuna"
    },
    {
     "expr": "mosdns_plugin_cache_query_total{instance=\"localhost:9080\"}",
     "legendFormat": "total"
    }
   ]
  },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Up",
   "type": "stat",
   "description": "Up Time",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{job=\"mosdns\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "description": "Up Time",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"mosdns\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cache Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mosdns_plugin_cache_cache_size{job=\"mosdns\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total query",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mosdns_plugin_cache_query_total{job=\"mosdns\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total cache hit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mosdns_plugin_cache_hit_total{job=\"mosdns\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total lazy hit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mosdns_plugin_cache_lazy_hit_total{job=\"mosdns\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Resident memory",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"mosdns\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "timeseries",
   "description": "Resident memory",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"mosdns\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines/Threads",
   "type": "timeseries",
   "description": "Number of goroutines and threads that currently exist",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"mosdns\"}",
     "legendFormat": "goroutines {{instance}}"
    },
    {
     "expr": "go_threads{job=\"mosdns\"}",
     "legendFormat": "threads {{instance}}"
    }
   ]
  },
  {
   "title": "Open Files",
   "type": "timeseries",
   "description": "Current Number of Open File Descriptors",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "process_max_fds{job=\"mosdns\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "process_open_fds{job=\"mosdns\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "mosdns", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Cache size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 28 },
   "targets": [
    { "expr": "mosdns_cache_size_current", "legendFormat": "{{instance}}" },
    { "expr": "mosdns_plugin_cache_cache_size", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Query per minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 28 },
   "targets": [
    { "expr": "mosdns_cache_query_total", "legendFormat": "{{instance}}" },
    {
     "expr": "rate(mosdns_plugin_cache_query_total[60s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cache Hit Per minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "rate(mosdns_cache_hit_total[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "rate(mosdns_plugin_cache_hit_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cache Lazy Hit Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 28 },
   "targets": [
    { "expr": "mosdns_cache_lazy_hit_total", "legendFormat": "{{instance}}" },
    {
     "expr": "rate(mosdns_plugin_cache_lazy_hit_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}